project:
  type: website

website:
  page-navigation: true
  title: "IME05-06251-EQ"
  description: "Estatística da Qualidade"

  page-footer:
    left: "Baseado em https://sta210-s22.github.io/website/"
    background: "#D9E3E4"
    
  sidebar:
    background: "#D9E3E4"
    logo: "images/md.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/raccioly20
        text: "GitHub"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Informação da disciplina"
        contents:
          - href: visao-do-curso.qmd
            text: "Visão Geral"
          - href: index.qmd
            text: Cronograma
      - section: "Sobre"
        contents:
          - href: about.qmd
            text: Sobre
      - section: "RStudio Cloud"
        contents:
          - href: acesso-rstudio.qmd
            text: Acesso
      - section: "Conteúdo Semanal"
        contents:
          - href: semanas/Aula01.qmd
            text: "Explorando 01"
          - href: semanas/Aula01A.qmd
            text: "Explorando 02"
          - href: semanas/Aula02.qmd
            text: "Explorando 03"
          - href: semanas/Aula03.qmd
            text: "Ferramentas de Análise"
          - href: semanas/Aula04.qmd
            text: "GC da Média e Amplitude"
          - href: semanas/Aula05.qmd
            text: "GC da Média e Desvio"
          - href: semanas/Aula06.qmd
            text: "GC da Fração Não Conforme"
          - href: semanas/Aula07.qmd
            text: "GC da Número de Defeitos"
          - href: semanas/Aula08.qmd
            text: "Plano de Auditoria por Amostragem Simples"
          - href: semanas/Aula09.qmd
            text: "Plano de Auditoria por Amostragem Dupla"
          - href: semanas/Aula10.qmd
            text: "Comparação PAAS e PAAD"
          - href: semanas/Aula11.qmd
            text: "Plano Sequencial"
          
          
          

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual

