---
title: "PAAD"
author: "Ricardo Accioly"
date: ' `r Sys.Date()` '
format:
 html:
    code-link: true
    fig-width: 9
    fig-height: 7
    fig-dpi: 300
knitr:
  opts_chunk: 
    out.width: 90%
    comment: "#>"
execute:
  freeze: auto
---

## Biblioteca

```{r}
library(AcceptanceSampling)
```

## PAAD - Poisson

Neste caso não podemos mais usar a função find.plan, pois ela só serve para os PAAS.

Aqui vamos precisar de usar a tabela de Schilling e Johnson para definir o plano de auditoria.

```{r}
# p1=0,01
# p2 = 0,05
# alfa = 0.05
# beta = 0.10
# p2/p1 = 5
# Plano 3D a1=1 a2=4 r1=4 e r2=5 n1=n2=88
paad <- OC2c(n=c(88,88),c=c(1,4),r=c(4,5),type="poisson",pd=seq(0,.15,.01))
assess(paad,PRP=c(.01,.95),CRP=c(.05,.10))

```

## CCO - PAAD

```{r}
library(ggplot2)
cco_paad <- data.frame(pd=paad@pd, Pa=paad@paccept)
# Grafico de CCO
ggplot(cco_paad, aes(x=pd, y=Pa)) +
  geom_line() +
  labs(title="Curva de CCO - PAAD",
       x="Proporção de Não Conformes (pd)",
       y="Probabilidade de Aceitação (Pa)") +
  theme_minimal() +
  scale_x_continuous(breaks=seq(0, 0.15, by=0.01)) +
  scale_y_continuous(breaks=seq(0, 1, by=0.1))
```
